baseURL = 'https://idealboulevard.com/'
languageCode = 'zh-cn'
title = '理想之路'
theme = 'hugo-book'
publishDir = "./docs"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'light'

  BookToC = true

  BookMenuBundle = '/menu'

  BookSection = 'docs'

  BookEditPath = 'edit/main/exampleSite'

  BookDateFormat = '2006-01-02'

  BookSearch = false

  BookComments = true

  BookPortableLinks = true

  BookServiceWorker = true

  BookTranslatedOnly = false